RUNTIME ERROR: xxx
-------------------------------------------------
	testdata/error_in_object_local:1:20-29	function <anonymous>

{ local foo(bar) = error bar, baz: foo("xxx") }

-------------------------------------------------
	testdata/error_in_object_local:1:36-46	object <anonymous>

{ local foo(bar) = error bar, baz: foo("xxx") }

-------------------------------------------------
	During manifestation	


